// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegjistriCivil.Models;

namespace RegjistriCivil.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200518161952_AddedFamilyMembersSet")]
    partial class AddedFamilyMembersSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegjistriCivil.Models.BirthCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocumentIssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentIssuingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FatherDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("MotherDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("Municipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FatherDetailsId");

                    b.HasIndex("MotherDetailsId");

                    b.HasIndex("PersonId");

                    b.ToTable("BirthCertificates");
                });

            modelBuilder.Entity("RegjistriCivil.Models.DeathCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentIssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentIssuingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Municipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PlaceOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SpouseId");

                    b.ToTable("DeathCertificates");
                });

            modelBuilder.Entity("RegjistriCivil.Models.FamilyCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentIssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentIssuingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Municipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("FamilyCertificates");
                });

            modelBuilder.Entity("RegjistriCivil.Models.FamilyMemberBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FamilyMembers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FamilyMemberBase");
                });

            modelBuilder.Entity("RegjistriCivil.Models.IdCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocumentIssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentIssuingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Residence")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("IdCards");
                });

            modelBuilder.Entity("RegjistriCivil.Models.MarriageCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfMarriage")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentIssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentIssuingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HusbandFatherId")
                        .HasColumnType("int");

                    b.Property<int?>("HusbandId")
                        .HasColumnType("int");

                    b.Property<int?>("HusbandMotherId")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Municipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfMarriage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WifeFatherId")
                        .HasColumnType("int");

                    b.Property<int?>("WifeId")
                        .HasColumnType("int");

                    b.Property<int?>("WifeMotherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HusbandFatherId");

                    b.HasIndex("HusbandId");

                    b.HasIndex("HusbandMotherId");

                    b.HasIndex("WifeFatherId");

                    b.HasIndex("WifeId");

                    b.HasIndex("WifeMotherId");

                    b.ToTable("MarriageCertificates");
                });

            modelBuilder.Entity("RegjistriCivil.Models.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocumentIssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentIssuingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EyeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("RegjistriCivil.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalNumber")
                        .HasColumnType("int");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("RegjistriCivil.Models.PersonStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employment")
                        .HasColumnType("int");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<int>("Migration")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PlaceOfMigration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolQualification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonStatistics");
                });

            modelBuilder.Entity("RegjistriCivil.Models.FamilyMember", b =>
                {
                    b.HasBaseType("RegjistriCivil.Models.FamilyMemberBase");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FamilyMember");
                });

            modelBuilder.Entity("RegjistriCivil.Models.FamilyMemberWithRelation", b =>
                {
                    b.HasBaseType("RegjistriCivil.Models.FamilyMember");

                    b.Property<int?>("FamilyCertificateId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalNumber")
                        .HasColumnType("int");

                    b.Property<int>("Relation")
                        .HasColumnType("int");

                    b.HasIndex("FamilyCertificateId");

                    b.HasDiscriminator().HasValue("FamilyMemberWithRelation");
                });

            modelBuilder.Entity("RegjistriCivil.Models.BirthCertificate", b =>
                {
                    b.HasOne("RegjistriCivil.Models.FamilyMember", "FatherDetails")
                        .WithMany()
                        .HasForeignKey("FatherDetailsId");

                    b.HasOne("RegjistriCivil.Models.FamilyMember", "MotherDetails")
                        .WithMany()
                        .HasForeignKey("MotherDetailsId");

                    b.HasOne("RegjistriCivil.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("RegjistriCivil.Models.DeathCertificate", b =>
                {
                    b.HasOne("RegjistriCivil.Models.FamilyMemberBase", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId");

                    b.HasOne("RegjistriCivil.Models.FamilyMemberBase", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId");

                    b.HasOne("RegjistriCivil.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("RegjistriCivil.Models.FamilyMemberBase", "Spouse")
                        .WithMany()
                        .HasForeignKey("SpouseId");
                });

            modelBuilder.Entity("RegjistriCivil.Models.FamilyCertificate", b =>
                {
                    b.HasOne("RegjistriCivil.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("RegjistriCivil.Models.IdCard", b =>
                {
                    b.HasOne("RegjistriCivil.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("RegjistriCivil.Models.MarriageCertificate", b =>
                {
                    b.HasOne("RegjistriCivil.Models.FamilyMemberBase", "HusbandFather")
                        .WithMany()
                        .HasForeignKey("HusbandFatherId");

                    b.HasOne("RegjistriCivil.Models.Person", "Husband")
                        .WithMany()
                        .HasForeignKey("HusbandId");

                    b.HasOne("RegjistriCivil.Models.FamilyMemberBase", "HusbandMother")
                        .WithMany()
                        .HasForeignKey("HusbandMotherId");

                    b.HasOne("RegjistriCivil.Models.FamilyMemberBase", "WifeFather")
                        .WithMany()
                        .HasForeignKey("WifeFatherId");

                    b.HasOne("RegjistriCivil.Models.Person", "Wife")
                        .WithMany()
                        .HasForeignKey("WifeId");

                    b.HasOne("RegjistriCivil.Models.FamilyMemberBase", "WifeMother")
                        .WithMany()
                        .HasForeignKey("WifeMotherId");
                });

            modelBuilder.Entity("RegjistriCivil.Models.Passport", b =>
                {
                    b.HasOne("RegjistriCivil.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("RegjistriCivil.Models.PersonStatistic", b =>
                {
                    b.HasOne("RegjistriCivil.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("RegjistriCivil.Models.FamilyMemberWithRelation", b =>
                {
                    b.HasOne("RegjistriCivil.Models.FamilyCertificate", null)
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyCertificateId");
                });
#pragma warning restore 612, 618
        }
    }
}
